baseURL = "https://cv.rso.com"
languageCode = "en-us"
title = "Rafael Serra e Oliveira's Curriculum Vitae"
disableKinds = [
	"page",
	"section",
	"taxonomy",
	"term",
	"RSS",
	"sitemap",
	"robotsTXT",
]

defaultContentLanguage = "en"
[languages]
[languages.en]
languageName = "English"
weight = 1
[languages.en.params]
datasource = "content.en"
[languages.pt]
languageName = "Portuguese"
weight = 2
[languages.pt.params]
datasource = "content.pt"
